environment: {}
parameters: {}
packages:
  - name: freshapi
    environment: {}
    parameters: {}
    annotations: {}
    functions:
      - name: graphql
        binary: false
        main: ''
        runtime: 'nodejs:18'
        web: true
        parameters: {}
        environment:
          FRESHTEAM_DOMAIN: "${FRESHTEAM_DOMAIN}"
          FRESHTEAM_TOKEN: "${FRESHTEAM_TOKEN}"
          TOKEN: "${TOKEN}"
        annotations: {}
        limits:
          timeout: 10000
